### ISSUE TITLE
When walking blob storage, most chunk options don't apply to folders

### ISSUE THREAD

**Issue by gadomski** [microsoft/planetary-computer-tasks#80]
**Describe the bug**
The path filter that applies the extensions, ends_with, and matches filters is only applied to files, not folders: https://github.com/microsoft/planetary-computer-tasks/blob/1ecd3ad75931705a9edf102b73507a85b7bd1afa/pctasks/core/pctasks/core/storage/blob.py#L478

The same is true for `limit`, though limit is enforced elsewhere, not in the path filter.

This makes it hard to control how many chunk lines you're creating if you're only looking for folders.

**To reproduce**

To demonstrate that `limit` doesn't work:

```yaml
    asset_storage:
      - uri: blob://noaacdr/ocean-heat-content
        chunks:
          options:
            name_starts_with: data
            list_folders: true
            limit: 1
```

This finds all four folders in `data/` and saves them to a single chunk file.

**Expected behavior**
All chunk creation options should apply the same to files and folders.

**Additional context**
This will require a non-trivial rewrite of `walk` in blob storage, I think.
